# Generated by Django 4.1.4 on 2022-12-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("phone_num", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
