# Generated by Django 4.1.4 on 2022-12-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
