# Generated by Django 4.1.4 on 2022-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name_plural": "my jobs"},
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                default="Full Time",
                max_length=20,
            ),
        ),
    ]
