# Generated by Django 4.1.4 on 2022-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_job_options_job_job_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name_plural": "Jobs"},
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.TimeField(auto_now=True),
        ),
    ]
