# Generated by Django 4.1.4 on 2022-12-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_job_options_job_description_job_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                default="",
                max_length=20,
            ),
        ),
    ]
