# Generated by Django 4.1.4 on 2022-12-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_alter_job_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Vacancy",
            field=models.IntegerField(default=1),
        ),
    ]
