# Generated by Django 4.1.4 on 2022-12-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_job_vacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
