# Generated by Django 4.1.4 on 2022-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_alter_job_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
    ]
