# Generated by Django 4.1.4 on 2022-12-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_job_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/"),
            preserve_default=False,
        ),
    ]
