# Generated by Django 4.1.4 on 2022-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0013_job_slug_alter_job_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("website", models.URLField(blank=True, null=True)),
                ("cv", models.FileField(upload_to="apply/")),
                ("cover_letter", models.TextField(max_length=600)),
            ],
        ),
    ]
