# Generated by Django 4.1.4 on 2022-12-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0014_apply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apply",
            options={"verbose_name_plural": "Applies"},
        ),
        migrations.AddField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apply_job",
                to="job.job",
            ),
            preserve_default=False,
        ),
    ]
