# Generated by Django 4.1.4 on 2022-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0015_alter_apply_options_apply_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="cerated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
